### ISSUE TITLE
Add "mode" parameter to googleCalendar extension

### ISSUE THREAD

**Issue by jcfr** [Slicer/mediawiki-extensions#1]
@adamrankin What do you think of adding an optional mode parameter to the `googleCalendar` extension ? 

That would allow to change the default tab shown.

**Comment by adamrankin** [comment]
Yup yup yup. On it.

**Comment by adamrankin** [comment]
Not sure how to attach commits to issues. See https://github.com/Slicer/mediawiki-extensions/commit/ba0e722ddb1bb2cd42cc0cbfc8db85a243ca197c

**Comment by jcfr** [comment]
:+1:

**Comment by jcfr** [comment]
> Not sure how to attach commits to issues

See https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by jcfr** [comment]
And also https://github.com/blog/957-introducing-issue-mentions
